### ISSUE TITLE
CoRAL plot error

### ISSUE THREAD

**Issue by ucsfpan** [AmpliconSuite/CoRAL#16]
Hi author, 
Thanks for this great tool. I have run the command: 
/c4/home/ucsf-pan/software/CoRAL/src/CoRAL.py seed --cn_seg /bastianlab/data1/hpan/pacbio_ccs/CNVkit_m84127/m84127.mini.pacbioccs.cns
/c4/home/ucsf-pan/software/CoRAL/src/CoRAL.py reconstruct --lr_bam  /bastianlab/data1/hpan/pacbio_ccs/alignment_mini/m84127.mini.pacbioccs.bam --cnv_seed  /bastianlab/data1/hpan/pacbio_ccs/CNVkit_m84127/m84127.mini.pacbioccs_CNV_SEEDS.bed --output_prefix samp1 --cn_seg  /bastianlab/data1/hpan/pacbio_ccs/CNVkit_m84127/m84127.mini.pacbioccs.cns
/c4/home/ucsf-pan/software/CoRAL/src/CoRAL.py plot --ref GRCh38 --bam /bastianlab/data1/hpan/pacbio_ccs/alignment_mini/m84127.mini.pacbioccs.bam --graph amplicon1_graph.txt --cycles amplicon1_cycles.txt --output_prefix aa --plot_graph --plot_cycles

The first two steps are successful, and I got the output  GRCh38_CNV_SEEDS.bed Graph file Cycles file, but when I try to plot , it come out of such issue.  Would you please help me to solve this? Thanks!

Traceback (most recent call last):
  File "/c4/home/ucsf-pan/software/CoRAL/src/CoRAL.py", line 166, in <module>
    plot_mode(args)
  File "/c4/home/ucsf-pan/software/CoRAL/src/CoRAL.py", line 45, in plot_mode
    plot_amplicons.plot_amplicons(args)
  File "/c4/home/ucsf-pan/software/CoRAL/src/plot_amplicons.py", line 935, in plot_amplicons
    g.plot_graph(gtitle, args.output_prefix + "_graph", max_cov_cutoff=args.max_coverage, quality_threshold=args.min_mapq,
  File "/c4/home/ucsf-pan/software/CoRAL/src/plot_amplicons.py", line 573, in plot_graph
    plt.savefig(output_fn + ".png", dpi = dpi)
  File "/c4/home/ucsf-pan/miniconda3/envs/CoRAL/lib/python3.9/site-packages/matplotlib/pyplot.py", line 1228, in savefig
    res = fig.savefig(*args, **kwargs)  # type: ignore[func-returns-value]
  File "/c4/home/ucsf-pan/miniconda3/envs/CoRAL/lib/python3.9/site-packages/matplotlib/figure.py", line 3395, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/c4/home/ucsf-pan/miniconda3/envs/CoRAL/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2204, in print_figure
    result = print_method(
  File "/c4/home/ucsf-pan/miniconda3/envs/CoRAL/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2054, in <lambda>
    print_method = functools.wraps(meth)(lambda *args, **kwargs: meth(
  File "/c4/home/ucsf-pan/miniconda3/envs/CoRAL/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 496, in print_png
    self._print_pil(filename_or_obj, "png", pil_kwargs, metadata)
  File "/c4/home/ucsf-pan/miniconda3/envs/CoRAL/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 444, in _print_pil
    FigureCanvasAgg.draw(self)
  File "/c4/home/ucsf-pan/miniconda3/envs/CoRAL/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 387, in draw
    self.figure.draw(self.renderer)
  File "/c4/home/ucsf-pan/miniconda3/envs/CoRAL/lib/python3.9/site-packages/matplotlib/artist.py", line 95, in draw_wrapper
    result = draw(artist, renderer, *args, **kwargs)
  File "/c4/home/ucsf-pan/miniconda3/envs/CoRAL/lib/python3.9/site-packages/matplotlib/artist.py", line 72, in draw_wrapper
    return draw(artist, renderer)
  File "/c4/home/ucsf-pan/miniconda3/envs/CoRAL/lib/python3.9/site-packages/matplotlib/figure.py", line 3161, in draw
    self.patch.draw(renderer)
  File "/c4/home/ucsf-pan/miniconda3/envs/CoRAL/lib/python3.9/site-packages/matplotlib/artist.py", line 72, in draw_wrapper
    return draw(artist, renderer)
  File "/c4/home/ucsf-pan/miniconda3/envs/CoRAL/lib/python3.9/site-packages/matplotlib/patches.py", line 632, in draw
    self._draw_paths_with_artist_properties(
  File "/c4/home/ucsf-pan/miniconda3/envs/CoRAL/lib/python3.9/site-packages/matplotlib/patches.py", line 617, in _draw_paths_with_artist_properties
    renderer.draw_path(gc, *draw_path_args)
  File "/c4/home/ucsf-pan/miniconda3/envs/CoRAL/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 131, in draw_path
    self._renderer.draw_path(gc, path, transform, rgbFace)
ValueError: object __array__ method not producing an array.

**Comment by GenomeArch** [comment]
Hi, Thanks for the great tool. I'm curious about a scenario involving the same cell line where Coral use long-read sequencing detects ecDNA, yet short-read sequencing with the Amplicon Suite does not. Can we still regard these as true ecDNA instances?"

**Comment by jluebeck** [comment]
Hi, 

This is an interesting case. It's hard to say without seeing the outputs of both tools why this disagreement would happen. It could be that long reads detected more structural variants than short reads and did a better job reconstructing, or it could be a false positive. It is also good to note that if the short and long reads are not generated contemporaneously, then evolution of the sample  over time may lead to differences in the observed amplification events.

Thanks,
Jens

**Comment by GenomeArch** [comment]
Thanks for your clarification.
