### ISSUE TITLE
No module named 'intervaltree'

### ISSUE THREAD

**Issue by ryao-mdanderson** [AmpliconSuite/CoRAL#5]
Dear CoRAL author:

After I installed all prerequisites pkgs (pysam, cvxopt, cnvkit)  inside a conda environment, I hit an error message to run the following command.
 $ python3 src/infer_breakpoint_graph.py -h
 Traceback (most recent call last):
  File "/rsrch3/home/itops/ryao/CoRAL/src/infer_breakpoint_graph.py", line 9, in <module>
    import intervaltree
 ModuleNotFoundError: No module named 'intervaltree'

 I do both methods inside the conda env:
 1, pip install intervaltree
 or
 2) conda install intervaltree

 The installation is successful, however, the above error message does not resolve.
 Any suggestion?

Thank you very much!

**Comment by jluebeck** [comment]
Hi, can you confirm that the intervaltree package is installed into the specific environment you created? 
`conda list -n [myenv]`

**Comment by ryao-mdanderson** [comment]
Hello @jluebeck , thank you for replying.

Yes, I am able to find the packages in the conda environment I created:

(coral-1.0.0) [ris_hpc_apps@ldragon4 ~]$ conda list -n coral-1.0.0
# packages in environment at /risapps/rhel8/miniconda3/py39_4.12.0/envs/coral-1.0.0:
...
cnvkit                    0.9.10             pyhdfd78af_0    bioconda
coral                     1.0.0                hf5e1fbb_1    bioconda
cvxopt                    1.3.2           py310h14a12bf_1    conda-forge
intervaltree              3.1.0              pyhd8ed1ab_1    conda-forge
...

**Comment by jluebeck** [comment]
Interesting - this is indeed a mystery then. If you enter a `python3` interactive session and do `import intervaltree`, do you encounter the error? 

I will try to recreate this error locally in the next few days if it is not resolved due to some simple pathing issue.

**Comment by ryao-mdanderson** [comment]
In an interactive session - import intervaltree works for the service account (ris_hpc_apps) that installed the conda env coral-1.0.0, but hit another error later:

(coral-1.0.0) [ris_hpc_apps@ldragon4 ~]$ python3
Python 3.10.8 | packaged by conda-forge | (main, Nov 22 2022, 08:23:14) [GCC 10.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import intervaltree
>>> exit()

But hit an error for 
(coral-1.0.0) [ris_hpc_apps@ldragon4 CoRAL]$ python3 src/infer_breakpoint_graph.py -h
Traceback (most recent call last):
  File "/risapps/ris_hpc_apps/CoRAL/src/infer_breakpoint_graph.py", line 15, in <module>
    from cycle_decomposition import *
  File "/risapps/ris_hpc_apps/CoRAL/src/cycle_decomposition.py", line 6, in <module>
    import gurobipy as gp
ModuleNotFoundError: No module named 'gurobipy'
 -- I think I missed to install gurobipy, there is no conda pkg gurobipy, I need to install it following Gurobi website?

 The service account installs the conda environment, on HPC cluster, we usually create a module of this conda environment to allow cluster user (other than the service account) to use the module, in an interactive session, regular cluster user (e.g ryao) seems not able to find intervaltree, this is the test:

(coral-1.0.0) [ryao@ldragon4 CoRAL]$ python3
Python 3.10.8 | packaged by conda-forge | (main, Nov 22 2022, 08:23:14) [GCC 10.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import intervaltree
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'intervaltree'

If you identify anything that I have overlooked, please advise. Thank you!

**Comment by jluebeck** [comment]
Thanks for this info, very helpful!

I believe that because you installed with one account (ris_hpc_apps) and are running with another (ryao), it is not finding the library files properly. Please install the libraries as the account you will run as.

For Gurobi, please follow the instructions here:
https://support.gurobi.com/hc/en-us/articles/4534161999889-How-do-I-install-Gurobi-Optimizer

You will also need to install this as the account you are running the tool as (and add the bashrc variables to your own .bashrc file, not some other account.

We will attempt to further automate these installation instructions in the coming weeks.

**Comment by ryao-mdanderson** [comment]
I figured out the reason. Please close this issue report.
Again, thank you very much for your help!

**Comment by ryao-mdanderson** [comment]
Hello @jluebeck 
 Just to update the reason: Because I initially installed coral conda environment in my personal conda location ($HOME/.conda/env/coral-1.0.0)  before proceed to install as a service account, and, in my personal conda location, I did not install intervaltree there. The fact is, using conda, my personal conda takes priority

Thanks for the gurobi python tip.
