### ISSUE TITLE
chimeric_alignments error during infer_breakpoint_graph

### ISSUE THREAD

**Issue by Tina04021997** [AmpliconSuite/CoRAL#7]
Thank you all for developing CoRAL. I have a question regarding the error message during infer_breakpoint_graph step and wonder if there are any suggestions you could kindly have:

Error message:
Traceback (most recent call last):
  File "/tscc/nfs/home/tiy002/software/CoRAL/src/infer_breakpoint_graph.py", line 1637, in <module>
    b2bn.find_amplicon_intervals()
  File "/tscc/nfs/home/tiy002/software/CoRAL/src/infer_breakpoint_graph.py", line 219, in find_amplicon_intervals
    self.find_interval_i(ai, ccid)
  File "/tscc/nfs/home/tiy002/software/CoRAL/src/infer_breakpoint_graph.py", line 354, in find_interval_i
    if i in self.chimeric_alignments_seg[chr]:
KeyError: 'chr1'

The last few lines of the  log file:
[root:DEBUG]    #TIME 332.1212          Updated amplicon interval ['chr12', 56855263, 57175262, -1]
[root:DEBUG]    #TIME 332.1212          Updated amplicon interval ['chr12', 57555264, 57950263, -1]
[root:DEBUG]    #TIME 332.1212          Updated amplicon interval ['chr12', 68545270, 69760270, -1]
[root:DEBUG]    #TIME 332.1213          Updated amplicon interval ['chr12', 110075295, 110390294, -1]
[root:DEBUG]    #TIME 332.1213  Begin processing amplicon interval 0
[root:DEBUG]    #TIME 332.1213          Amplicon interval ['chr1', 766225, 1086326, -1]
[root:DEBUG]    #TIME 332.1213          Start BFS on amplicon interval 0.
[root:DEBUG]    #TIME 332.1213                  BFS queue: [0]
[root:DEBUG]    #TIME 332.1213                  Next amplicon interval 0: ['chr1', 766225, 1086326, -1].
[root:DEBUG]    #TIME 332.1214                  Reset connected component ID to 0

CoRAL Command:
python3 /tscc/nfs/home/tiy002/software/CoRAL/src/infer_breakpoint_graph.py --lr_bam $PATH/TR14.mkdup.bam --seed $PATH/TR14_CNV_SEEDS.bed --output_prefix $PATH/TR14 --cnseg $PATH/TR14.mkdup.cns --log_fn TR14_trace.log

CNVkit command:
cnvkit.py batch -m wgs -r /tscc/nfs/home/tiy002/data_repo/GRCh38/GRCh38_cnvkit_filtered_ref.cnn -p 16 -d $PATH/cnvkit $PATH/TR14.mkdup.bam

Additional info:
1. Both CNV_SEEDS.bed and cns files were generated via cnv_seed.py
2. This is a tumor cell line long-read seq sample (PacBio) without matched normal 
3. Key steps for long-read seq data preprocessing (using PacBio tool smrtlink):
    a) BAM to FASTQ
    b) FASTQ alignment to BAM (PacBio CCS mode)
    c) Sort and index and perform mark duplicate

**Comment by MJoseMo** [comment]
@Tina04021997 
I have a similar problem when running CoRaL.py reconstruct, I was wondering if you were able to fix it. 
Traceback (most recent call last):

`  File «/ngs/coral_soft/CoRAL/src/CoRAL.py», line 150, in <module>
    reconstruct_mode(args)
  File «/ngs/coral_soft/CoRAL/src/CoRAL.py», line 23, in reconstruir_modo
    infer_breakpoint_graph.reconstruir(args)
  File «/ngs/coral_soft/CoRAL/src/infer_breakpoint_graph.py», line 1630, in reconstruir
    b2bn.find_amplicon_intervals()
  File «/ngs/coral_soft/CoRAL/src/infer_breakpoint_graph.py», line 224, in find_amplicon_intervals
    self.find_interval_i(ai, ccid)
  File «/ngs/coral_soft/CoRAL/src/infer_breakpoint_graph.py», line 362, in find_interval_i
    if i in self.chimeric_alignments_seg[chr]:
KeyError: 'chr5'
`

**Comment by Jenny-Tamboli** [comment]
Hi Team CoRAL,

I have encountered almost similar issues as well while running reconstruct mode. I am using Nanopore reads aligned with NGMLR (which is in contrast to minimap2 mentioned in the article). The log file (error message attached) shows some key error corresponding to parsing the CIGAR string in bam files. 

`Performing reconstruction with options:
mode: reconstruct
lr_bam: /data/cephfs-1/work/projects/ecdnapanc/carcinoma_celllines/Panc1_20230711_sorted.bam
cnv_seed: /data/cephfs-1/work/projects/ecdnapanc/CoRAL/outputs/seed_mode/Panc1_20230711_sorted_CNV_SEEDS.bed
output_prefix: /data/cephfs-1/work/projects/ecdnapanc/CoRAL/outputs/reconstruct_mode/Panc1_20230711_sorted
cn_seg: /data/cephfs-1/work/projects/ecdnapanc/carcinoma_celllines/cnvkit/calls/Panc1_20230711_sorted.call.cns
output_bp: False
skip_cycle_decomp: False
output_all_path_constraints: False
min_bp_support: 1.0
cycle_decomp_alpha: 0.01
cycle_decomp_time_limit: 7200
cycle_decomp_threads: None
postprocess_greedy_sol: False
log_fn: None

Traceback (most recent call last):
  File "/data/cephfs-1/work/projects/ecdnapanc/CoRAL/src/CoRAL.py", line 162, in <module>
    reconstruct_mode(args)
  File "/data/cephfs-1/work/projects/ecdnapanc/CoRAL/src/CoRAL.py", line 25, in reconstruct_mode
    b2bn = infer_breakpoint_graph.reconstruct_graph(args)
  File "/data/cephfs-1/work/projects/ecdnapanc/CoRAL/src/infer_breakpoint_graph.py", line 1356, in reconstruct_graph
    b2bn.fetch()
  File "/data/cephfs-1/work/projects/ecdnapanc/CoRAL/src/infer_breakpoint_graph.py", line 171, in fetch
    self.chimeric_alignments[r] = cigar_parsing.alignment_from_satags(self.chimeric_alignments[r], rl)
  File "/data/cephfs-1/work/projects/ecdnapanc/CoRAL/src/cigar_parsing.py", line 255, in alignment_from_satags
    qs, qe, al = cigar2pos_ops[op](t[3], t[2], read_length)
KeyError: 'SMDMIMDMDMDMIMDMDMDMDMDMDMDMDMDMDMDMDMDMIMIMDMDMIMIMDMDMDMDMDMDMDMDMDMIMDMDMDMDMIMIMDMDMDMDMIMIMIMIMIMIMIMDMIMDMDMDMDMDMDMDMDMDMIMDMDMDMDMDMDMIMDMIMDMIMDMDMIMDMIMDMDMDMIMIMIMDMDMDMIMIMDMDMDMDMIMIMDMIMDMDMIMIMDMIMDMDMDMIMDMIMIMDMIMDMDMS'
`
I am also attaching log messages from infer_breakpoint_graph.log file.

`[root:INFO]     Python version 3.7.12 | packaged by conda-forge | (default, Oct 26 2021, 06:08:21) 
[GCC 9.4.0]

[root:INFO]     #TIME 0.0046    Commandline: /data/cephfs-1/work/projects/ecdnapanc/CoRAL/src/CoRAL.py reconstruct --lr_bam /data/cephfs-1/work/projects/ecdnapanc/carcinoma_celllines/Panc1_20230711_sorted.bam --cnv_seed /data/cephfs-1/work/projects/ecdnapanc/CoRAL/outputs/seed_mode/Panc1_20230711_sorted_CNV_SEEDS.bed --output_prefix /data/cephfs-1/work/projects/ecdnapanc/CoRAL/outputs/reconstruct_mode/Panc1_20230711_sorted --cn_seg /data/cephfs-1/work/projects/ecdnapanc/carcinoma_celllines/cnvkit/calls/Panc1_20230711_sorted.call.cns 
[root:DEBUG]    #TIME 0.1048    Parsed 1 seed amplicon intervals.
[root:DEBUG]    #TIME 0.1051    Seed interval ['chr19', 38636506, 40851628]
[root:INFO]     #TIME 0.1051    Opened LR bam files.
[root:DEBUG]    #TIME 0.1494    Total num LR copy number segments: 1533.
[root:DEBUG]    #TIME 0.1497    Use 22 LR copy number segments.
[root:DEBUG]    #TIME 0.1498    Total length of LR copy number segments: 12454852.
[root:DEBUG]    #TIME 0.1498    Average LR copy number: -0.094312.
[root:INFO]     #TIME 36.1310   LR normal cov = 13.925882.
[root:DEBUG]    #TIME 36.1311   Reset min_cluster_cutoff to 13.925882.
[root:INFO]     #TIME 36.1312   Completed parsing CN segment files.
[root:INFO]     #TIME 746.4804  Fetched 375886 chimeric reads.
`

Could you please guide how to solve this issue?
Thanks in advance!

**Comment by MJoseMo** [comment]
Hi @Jenny-Tamboli, I think it could only be used with winnowmap. We aligned our data with winnowmap and printed different variables of the script infer_breakpoint_graph.py. With winnowmap, the read's name is printed (column 1) but not with pbmm2, maybe because of how winnowmap defines the CIGAR string. I have also tried this program by providing the seed and bed files and it also produces errors.

**Comment by mattjones315** [comment]
Hi all,

Thanks so much for using CoRAL and posting this issue!

Though in our study we used minimap2 for all alignments, there's no reason that alternative aligners will not work (such as winnowmap or NGMLR). I think that one issue could be the MarkDuplicates step - if you run CoRAL without this last filter (i.e., just alignment & sorting), does this fix the issue? If I understand your workflow correctly, you did not do any PCR amplifications I'm not sure marking/removing duplicates is necessary for this analysis. Apologies if I misunderstood something.

Best,
Matt

**Comment by MJoseMo** [comment]
Hi, 
I initially assumed that aligment of long-read sequences was performed with winnowmap, as it is indicated in align_nanopore_reads.sh (script folder). However, I noticed that minimap is mentioned in the draft paper. 
@Jenny-Tamboli in the software's description, it states that CNV and seed files could be provided without running the script call_cnvs.sh or the seed command. However, I encountered an error when these files are proportioned without running these previous steps.

**Comment by jluebeck** [comment]
Hi everyone, 

We have just released a testing version for CoRAL that supports both PacBio data and bams produced by aligners that make alternately formatted CIGARs (e.g. NGMLR). We would be greatful if you would be able to give it a try with the data you encountered that has issues. Please let me know if this gives errors for you and if so which aligner & long read technology you are using.

```
cd CoRAL
git fetch --all
git checkout pacbio_dev
git pull origin pacbio_dev
```

Thank you!
Jens

**Comment by MJoseMo** [comment]
Hi @jluebeck , did you recommend downsampling, at a specific coverage of 5x or 10x similar to Decoil?  Would it be possible to share code snippets of how the graphs were generated in the article, I've tried to replicate the results for  SRR28996237 (COLO320-DM_monoclonal_LR), though I've aligned it with winnowmap.

**Comment by MJoseMo** [comment]
Hi,

Has anyone attempted to use CoRAL with ngmlr aligner? It doesn’t finish the CN call (cnvkit.py).

**Comment by jluebeck** [comment]
Hi @MJoseMo  - 

Re : run parameters: We used minimap2 in the paper, however @kyzhu should be able to provide the choice of parameters used for COLO320-DM_monoclonal_LR (particularly what the read support cutoff was) and maybe provide the command he used.

Re: NGMLR, the CoRAL stage should work, however I have not tested CNVkit with NGMLR. What kind of error did it report? Users do not need to use CNVkit as the source of the CNV calls - if they have a preferred or better-performing caller for long read CNV analysis they can use a bed file output from that and CoRAL should automatically handle the bed input.

Thanks,
Jens

**Comment by jakelee0711** [comment]
Hi colleagues, this is Jake Lee at Memorial Sloan Kettering. Thank you so much for developing this great tool, which I look forward to running on the ONT sequencing data that we are actively generating. I am getting basically the same errors on the top of this thread. We used minimap2 for alignment with no mark duplication step, and the seed regions were generated by cnv_seed.py based on the CNVkit results. Any recent thoughts how I could troubleshoot the errors? Do you recommend any specific parameters while running CoRAL? Below I list my errors, log, and the CoRAL command to share more details. Thanks again for your great work and appreciate your help.

--Jake

Error message:
```python
Traceback (most recent call last):
  File "/data1/shahs3/users/leej39/tools/CoRAL/src/CoRAL.py", line 162, in <module>
    reconstruct_mode(args)
  File "/data1/shahs3/users/leej39/tools/CoRAL/src/CoRAL.py", line 25, in reconstruct_mode
    b2bn = infer_breakpoint_graph.reconstruct_graph(args)
  File "/data1/shahs3/users/leej39/tools/CoRAL/src/infer_breakpoint_graph.py", line 1360, in reconstruct_graph
    b2bn.find_amplicon_intervals()
  File "/data1/shahs3/users/leej39/tools/CoRAL/src/infer_breakpoint_graph.py", line 233, in find_amplicon_intervals
    self.find_interval_i(ai, ccid)
  File "/data1/shahs3/users/leej39/tools/CoRAL/src/infer_breakpoint_graph.py", line 433, in find_interval_i
    new_bp_list += alignment2bp(r, self.chimeric_alignments[r], self.min_bp_match_cutoff_,
  File "/data1/shahs3/users/leej39/tools/CoRAL/src/breakpoint_utilities.py", line 81, in alignment2bp
    bp_list.append(interval2bp(rr_int[ri], rr_int[ri + 1], (rn, ri, ri + 1), int(r_int[ri + 1][0]) - int(r_int[ri][1])) + [q_[ri], q_[ri + 1]])
  File "/data1/shahs3/users/leej39/tools/CoRAL/src/breakpoint_utilities.py", line 293, in interval2bp
    if (global_names.chr_idx[R2[0]] < global_names.chr_idx[R1[0]]) or (global_names.chr_idx[R2[0]] == global_names.chr_idx[R1[0]] and R2[1] < R1[2]):
KeyError: '8'

``` 

Last few lines of the log file: 
```python
[root:INFO]	#TIME 559.2807	Completed parsing CN segment files.
[root:INFO]	#TIME 1426.4441	Fetched 1807769 chimeric reads.
[root:INFO]	#TIME 1462.2654	Computed alignment intervals on all 1807769 chimeric reads.
[root:INFO]	#TIME 1462.2659	Completed fetching reads containing breakpoints.
[root:INFO]	#TIME 1501.8620	Completed hashing chimeric reads to CN segments.
[root:DEBUG]	#TIME 1501.8625	Updating seed amplicon intervals according to CN segments.
[root:DEBUG]	#TIME 1501.8627		Updated amplicon interval ['8', 116829223, 117157841, -1]
[root:DEBUG]	#TIME 1501.8629		Updated amplicon interval ['17', 27349751, 28173994, -1]
[root:DEBUG]	#TIME 1501.8631		Updated amplicon interval ['17', 31186014, 31836225, -1]
[root:DEBUG]	#TIME 1501.8632		Updated amplicon interval ['17', 32650150, 33383593, -1]
[root:DEBUG]	#TIME 1501.8634		Updated amplicon interval ['17', 37512372, 38851092, -1]
[root:DEBUG]	#TIME 1501.8635	Begin processing amplicon interval 0
[root:DEBUG]	#TIME 1501.8636		Amplicon interval ['8', 116829223, 117157841, -1]
[root:DEBUG]	#TIME 1501.8638		Start BFS on amplicon interval 0.
[root:DEBUG]	#TIME 1501.8639			BFS queue: [0]
[root:DEBUG]	#TIME 1501.8640			Next amplicon interval 0: ['8', 116829223, 117157841, -1].
[root:DEBUG]	#TIME 1501.8641			Reset connected component ID to 0
[root:DEBUG]	#TIME 1501.8747			Found new intervals on chr 8
[root:DEBUG]	#TIME 1501.8752			Refining new interval ['8', 115839744, 117296164].

``` 

CoRAL command: `/data1/shahs3/users/leej39/tools/CoRAL/src/CoRAL.py reconstruct --lr_bam /data1/shahs3/isabl_data_lake/analyses/24/43/42443/results/minimap2/SHAH_H003736_T02_01_WG01_R1.sorted.bam --cn_seg /data1/shahs3/users/leej39/ont/cnvkit/SHAH_H003736_GRCh37/SHAH_H003736_T02_01_WG01_R1.sorted.cns --cnv_seed SHAH_H003736_GRCh37/SHAH_H003736_GRCh37_CNV_SEEDS.bed --output_prefix SHAH_H003736_GRCh37/SHAH_H003736_GRCh37 --log_fn SHAH_H003736_GRCh37/SHAH_H003736_GRCh37.log --min_bp_support 10.0`

**Comment by jluebeck** [comment]
Hi Jake! 

Looks like this error arises due to use of GRCh37 (or some other build where the 'chr' prefix is not in front of chromosome names).  Currently, CoRAL only supports GRCh38, however this is a limitation which it is a very high priority for us to improve.

I will raise this issue at our next meeting and let you know when we plan to have that limitation resolved. In the meantime if you are able to re-map to GRCh38, then that should resolve the issue.

Thanks!
Jens

**Comment by jakelee0711** [comment]
Hi Jens, thank you so much for pointing this out. I will retry after aligning on GRCh38. Will keep you posted. --Jake

**Comment by jluebeck** [comment]
Very strange! However, stalling at the segmentation step can also happen if the Rscript version is not correct and/or the Rscript libraries used by CNVkit are not installed. Can you confirm that CNVkit is working  for you on another sample (e.g. some short reads aligned with BWA)?

If you suspect that the Rscript libraries used by CNVkit are not installed you can try these commands:

`Rscript --version  # should be 3.5 or higher`
 
`Rscript -e 'if (!require("BiocManager", quietly = TRUE)) install.packages("BiocManager")'`
`Rscript -e 'BiocManager::install("DNAcopy")'`

**Comment by MJoseMo** [comment]
Dear @jluebeck, I previously used the program and it worked, what version of DNAcopy should I have?

**Comment by jluebeck** [comment]
Ah, good to know. I don't think the DNAcopy library is the issue then. We will try to reproduce this issue locally. If the issue is specific to CNVkit there is not much we can do besides notify them via github. For now, I recommend trying to re-align with minimap2 which we know works with CNVkit. If re-alignment is not feasible, you could attempt using some other CNV caller, for instance [Spectre](https://github.com/fritzsedlazeck/Spectre).

**Comment by MJoseMo** [comment]
Dear @jluebeck, I had to specified the path for R and now it works perfect, thanks for the suggestion :). I'm currently trying to represent cycles but I encounter this error:  

`
CoRAL/src/plot_amplicons.py:898: UserWarning: Tight layout not applied. tight_layout cannot make Axes height small enough to accommodate all Axes decorations.
  plt.tight_layout()

`

**Comment by MJoseMo** [comment]
I have  generated the .cns file using the reference hg38full_ref_5k.cnn, would there be any issues if I later use the GRCh38 reference for visualizing cycles and graphs?  I would like to suggest if it would be possible to include CNN files for the other genomes available in CoRAL.py plot as  hg19, GRCh38, and mm10.

**Comment by jluebeck** [comment]
Hi, 

Regarding the UserWarning - I believe this is a harmless message from matplotlib, but please let me know if there is failure to produce a plot.

I do not see any reasons why using GRCh38 in downstream analyses is a problem. We are working on expanding reference genome version support as this is a commonly requested feature.

Thanks,
Jens

**Comment by MJoseMo** [comment]
Dear @jluebeck, I would like to ask which CN thresholds did you recommend for optimal results when searching seed amplification intervals. The default threshold (6.0) didn't generate any ranges, but reducing its value produced some intervals.  Thanks for addressing all my questions, I really appreciate your help.

**Comment by jluebeck** [comment]
Good question. It is very difficult to reliably detect ecDNA below the default threshold of CoRAL. Do you have otherwise strong reason to expect its existence at a particular location in the genome? If so, then you can consider adjusting thresholds/input seeds as needed to force CoRAL to study the region of interest. If there is not reason to strongly suspect an ecDNA at a given location, reducing thresholds will likely result in many more false positive amplicons.

Thanks,
Jens

**Comment by MJoseMo** [comment]
hi I was wondering which minimap2 option select for the samples used to evaluate CoRAL, selecting the option -ax map-ont would be correct.  I've noticed that depending on the version, it's recommended to use different preset (map-ont, lr:hq . v2.27 or later)

**Comment by jluebeck** [comment]
Regarding the `IndexError` error. Hard to debug without seeing the .cns file. Possibly a reference genome issue. Are you able to share the .cns file that gave this issue?

I recommend following the guidance from the minimap2 developers as to which flag to set if you are using PacBio or ONT data. The choice of flag for `-ax` should not be a source of issues.

Thanks,
Jens

**Comment by MJoseMo** [comment]
Hi, I show you the cns file. Concerning the selection of `-ax `argument, I asked because in the paper different kits, workflow and base calling differ between cell lines and didn't know if it could influence the selection of '-ax' option or other parameters. 

```
chromosome	start	end	gene	log2	depth	probes	weight	ci_lo	ci_hi
chr1	14941	125164598	-	0.16328	0.00143153	38	11642.7	-0.116969	0.493416
chr1	143279586	248946422	-	-1.12538	0.000190471	17	10136.9	-1.34343	-0.824128
chr2	10000	91800000	-	-0.312032	0.000728025	21	8717.16	-0.617144	0.0663851
chr2	96000000	242183529	-	-0.118999	0.00103838	35	14099.5	-0.376806	0.167748
chr3	10000	87800000	-	-0.930351	0.000357468	16	8489.18	-1.17742	-0.458927
chr3	94000000	198235559	-	1.22559	0.000333788	6	10056.2	0.938354	1.77381
chr4	65030	48200000	-	0.335538	0.00120141	13	4614.11	-0.100215	0.621076
chr4	51813950	190204555	-	-1.75191	0.000151549	15	13272.2	-2.34119	-1.30986
chr5	15000	46100000	-	0.959857	0.00373142	18	4413.87	0.689184	1.42877
chr5	51400000	181478259	-	-0.257984	0.00051227	27	12479.1	-0.474406	0.0100724
chr6	69999	58453888	-	-0.0553454	0.000923991	15	5645.52	-0.360112	0.344075
chr6	62600000	170730981	-	-0.266308	0.000186514	10	10404.3	-0.587804	-0.045459
chr7	10000	58100000	-	1.47174	0.00406551	19	5606.44	1.17434	1.78838
chr7	62106229	159335973	-	0.158631	0.000698719	21	9324.9	-0.0390552	0.463255
chr8	85007	43200000	-	0.263235	0.00138041	15	4067.85	-0.0145135	0.528789
chr8	47200000	145078636	-	0.114119	0.000375317	14	9444.35	-0.164749	0.314809
chr9	10000	42200000	-	0.49336	0.000885073	9	3969.69	0.00297884	1.08785
chr9	60518558	138324717	-	0.475211	0.00317837	29	7125.14	0.190872	0.74838
chr10	14999	38000000	-	0.695859	0.00145197	11	3690.45	0.430736	1.11816
chr10	41693521	133787422	-	-0.10672	0.000878958	18	8826.12	-0.357166	0.31408
chr11	60000	50821348	-	-0.263278	0.00118604	12	4892.44	-0.662664	0.370425
chr11	55800000	135076622	-	0.426067	0.0013026	18	7660.81	0.119647	0.773892
chr12	14999	33200000	-	0.387377	0.00132442	12	3203.99	0.152107	0.736251
chr12	37800000	133260308	-	-0.744551	0.000335063	20	9238.65	-1.14369	-0.483971
chr13	16110066	114354328	-	0.418251	0.000167679	5	9136.37	0.203967	0.996972
chr14	16045161	106883718	-	-0.892439	0.000174419	10	8426.36	-1.07509	-0.538654
chr15	17000000	101981189	-	0.507884	0.00181303	24	7713.32	0.339992	0.903047
chr16	10000	35300000	-	-1.0973	0.000410599	9	3270.46	-1.56844	-0.654162
chr16	46425679	90228345	-	0.752859	0.0035536	18	4236.94	0.420408	1.0961
chr17	99814	22700000	-	-0.91715	0.00110907	11	2146.77	-1.31646	-0.452223
chr17	27400000	83247441	-	0.193937	0.000659732	14	5338.88	-0.0862506	0.485262
chr18	10000	15400000	-	1.51063	0.00205364	5	1491.99	1.22351	1.92011
chr18	21500000	80258285	-	0.148817	0.000314329	8	5671.67	-0.130748	0.595648
chr19	60000	24200000	-	-1.1618	0.00069887	6	2325.15	-2.03935	-0.697075
chr19	28100000	58607616	-	0.6226	0.00460308	13	2930.79	0.205636	1.13037
chr20	70000	25700000	-	-0.987323	3.069e-05	1	2487.16	-0.987323	-0.987323
chr20	30400000	64334167	-	0.547457	0.00331699	13	3250.62	0.0161126	1.046
chr21	5020080	46699983	-	0.0372814	0.00130186	19	3438.55	-0.270007	0.224898
chr22	10510000	50803468	-	1.47742	0.0054737	12	3245.06	0.9028	1.88599
chrX	10000	58100000	-	-0.0186827	0.000586955	10	5148.5	-0.400355	0.290144
chrX	63800000	156025894	-	1.31934	0.00050826	10	8404.3	0.824744	1.85348
chrY	11043736	57212403	-	1.11541	0.00031825	2	1523.52	0.198674	1.75838

```

**Comment by jluebeck** [comment]
Thanks! I think I see the issue here (some chroms did not have any CN called for the p arm). We can make the seed script a bit safer for these kinds of cases.

The CN values here look to me to be very undersegmented. Everything on each arm is called as a single CN. Either there are no focal events (and no point in running CoRAL), or there is something wrong about the CN calling. Can I ask how this file was generated? What commands were run?

Thanks,
Jens

**Comment by MJoseMo** [comment]
Thanks @jluebeck , this is not a WGS, instead we have sequenced extrachromosomal DNA and filtered to retain certain reads.

**Comment by MJoseMo** [comment]
Thanks @jluebeck for your commitment, I  would like to ask if you are familiar with any other methods for ecDNA reconstruction when extrachromosomal DNA is sequenced.

**Comment by jluebeck** [comment]
You can check out [Decoil](https://github.com/madagiurgiu25/decoil-pre), or you could simply try running [Metaflye](https://github.com/mikolmogorov/Flye) on the sample. Prior to development of CoRAL and Decoil, Metaflye has been commonly used for ecDNA reconstruction.
